name: Data Synchronization

on:
  push:
    paths:
      - '_data/software_data.yml'

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert YAML to JSON
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          cat _data/software_data.yml | jq --slurp . > docs/data/software_data.json
      - name: Commit JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/data/software_data.json
          git commit -m "Update software data JSON" || echo "No changes to commit"
          git push

